### ISSUE TITLE
vue import error   Module parse failed

### ISSUE THREAD

**Issue by TomorrowLsn** [cyberconnecthq/js-cyberconnect#23]
Using vue.js to introduce CyberConnect, the following error occurs
![1648623593(1)](https://user-images.githubusercontent.com/26833351/160770848-8fc58362-87ab-4a2b-894e-13bb7683c3f5.png)

![1648623478(1)](https://user-images.githubusercontent.com/26833351/160770679-b584a5c9-7629-4bee-8eb4-2e76359c7455.png)
@jiayi1992

**Comment by jiayi1992** [comment]
Hi @TomorrowLsn! Thanks for helping us to find this. 
We don't directly import did-jwt at this point, but we will create a issue on their side.

**Comment by HappySean2845** [comment]
HI @TomorrowLsn you can add 
`transpileDependencies:['did-jwt']`
 in your vue.config.js to solve this question

**Comment by TomorrowLsn** [comment]
> 嗨@TomorrowLsn，你可以 `transpileDependencies:['did-jwt']` 在你的 vue.config.js 中添加来解决这个问题

thank you
