### ISSUE TITLE
When using Connect method, I get CORS issue

### ISSUE THREAD

**Issue by TomorrowLsn** [cyberconnecthq/js-cyberconnect#24]
![1649678957(1)](https://user-images.githubusercontent.com/26833351/162736725-96a09715-340e-4af1-836c-5e3248574290.jpg)

@jiayi1992

**Comment by TomorrowLsn** [comment]
![1649679771(1)](https://user-images.githubusercontent.com/26833351/162738457-2522ecd9-b75d-48c9-8c06-fbcc9b12d474.png)
When running on localhost:8080, there is no problem.
Switching to port 8081 will not work.
It seems to only work in the localhost:8080 environment

**Comment by TomorrowLsn** [comment]
@HappySean2845

**Comment by TomorrowLsn** [comment]
> 嗨@TomorrowLsn！现在我们只开放一些用于本地测试的端口，例如 localhost:3000-3003 或 8080，如果您想在生产环境中使用这些 api，我们需要将您的域添加到我们的 CORS 白名单中。您可以通过不和谐让我们知道：[https ://discord.com/channels/901233976138682388/901234908662468658](https://discord.com/channels/901233976138682388/901234908662468658)

discord shows no permission to send messages

**Comment by TomorrowLsn** [comment]
> 嗨@TomorrowLsn！现在我们只开放一些用于本地测试的端口，例如 localhost:3000-3003 或 8080，如果您想在生产环境中使用这些 api，我们需要将您的域添加到我们的 CORS 白名单中。您可以通过不和谐让我们知道：[https ://discord.com/channels/901233976138682388/901234908662468658](https://discord.com/channels/901233976138682388/901234908662468658)

Please describe this issue in the API documentation

**Comment by jiayi1992** [comment]
> > 嗨@TomorrowLsn！现在我们只开放一些用于本地测试的端口，例如 localhost:3000-3003 或 8080，如果您想在生产环境中使用这些 api，我们需要将您的域添加到我们的 CORS 白名单中。您可以通过不和谐让我们知道：[https ://discord.com/channels/901233976138682388/901234908662468658](https://discord.com/channels/901233976138682388/901234908662468658)
> 
> Please describe this issue in the API documentation

@TomorrowLsn yeah, we are working on our developer doc refactor, this issue will be included in the new version.

**Comment by jiayi1992** [comment]
> > 嗨@TomorrowLsn！现在我们只开放一些用于本地测试的端口，例如 localhost:3000-3003 或 8080，如果您想在生产环境中使用这些 api，我们需要将您的域添加到我们的 CORS 白名单中。您可以通过不和谐让我们知道：[https ://discord.com/channels/901233976138682388/901234908662468658](https://discord.com/channels/901233976138682388/901234908662468658)
> 
> discord shows no permission to send messages

I think you need to do the verification first in our discord then you can send the message.
