### ISSUE TITLE
When using Connect method, I get CORS issue

### ISSUE THREAD

**Issue by johnwise9** [cyberconnecthq/js-cyberconnect#25]
When using Connect method, I get CORS issue 

it works fine locally but when I push it on the main server I get CORS issue
<img width="656" alt="Screenshot 2022-04-11 at 14 00 33" src="https://user-images.githubusercontent.com/97042650/162781254-1eff2467-2d00-4209-939f-b47944d8aee1.png">

**Comment by TomorrowLsn** [comment]
hi i have this problem too  #24

**Comment by jiayi1992** [comment]
Hi @johnwise9 ! Now we only open some ports for local test like localhost:3000-3003 or 8080, and if you want to use the apis on the production environment, we need to add your domain into our CORS white list. You can let us know through the discord: https://discord.com/channels/901233976138682388/901234908662468658
